#-------------------------------
# General Site Settings
title: Elan Cooper
logo: # You can add own logo. For example '/images/logo.png'.
description: Home of Elan Cooper.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://elanjcoop.github.io" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Elan Cooper
  avatar: '/images/EJC.jpeg'


#-------------------------------
# Hero Settings
hero:
  title: Elan Cooper
  description: Memphian in NYC. Stack-agnostic software engineer. Hooper.
  image: '/images/skyline.png'


#-------------------------------
# Contact Settings
contact:
  email: elanjcoop@gmail.com # Add your email for contact form
  description: Have a question for me? Want to get in touch about one of my projects? Contact me! # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
# - {icon: "ion-logo-twitter", link: "https://twitter.com"}
# - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# - {icon: "ion-logo-instagram", link: "https://instagram.com"}
# - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# - {icon: "ion-logo-youtube", link: "https://youtube.com"}
- {icon: "ion-logo-github", link: "https://github.com/elanjcoop"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/elanjcoop/"}
# - {icon: "ion ion-logo-vimeo", link: "https://vimeo.com/"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: UA-183847540-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed